version: '3.9' # optional since v1.27.0
services:
  docker-db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    # command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
#     networks:
#       - mynet

  docker-backend:
    depends_on:
      - docker-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: docker-db
      SESSION_SECRET: ${SESSION_SECRET}
      FRONT_END_IP: ${FRONT_END_IP}
    # networks:
    #   - mynet
    volumes:
      - ./:/backend
      
  docker-phpmyadmin:
    depends_on:
      - docker-db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '5001:80'
    env_file: ./.env
    environment:
      PMA_HOST: docker-db 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#     networks:
#       - mynet

volumes:
  db_data: {}

# bridge network is the default one 
# networks:
#   mynet:
#     driver: bridge